// Generated from docs/info2update_items.csv and docs/info2update_facilities.csv. Do not edit by hand.
import type { FacilityConfig } from '../types';
import { ITEMS } from './items';

export const FACILITIES: FacilityConfig[] = [
  {
    id: "automation-core",
    name: "协议核心",
    nameEn: "Automation-Core",
    power: -200,
    width: 9,
    height: 9,
    inputs: [{"x":1,"y":0,"side":"top","kind":"item"},{"x":2,"y":0,"side":"top","kind":"item"},{"x":3,"y":0,"side":"top","kind":"item"},{"x":4,"y":0,"side":"top","kind":"item"},{"x":5,"y":0,"side":"top","kind":"item"},{"x":6,"y":0,"side":"top","kind":"item"},{"x":7,"y":0,"side":"top","kind":"item"},{"x":1,"y":8,"side":"bottom","kind":"item"},{"x":2,"y":8,"side":"bottom","kind":"item"},{"x":3,"y":8,"side":"bottom","kind":"item"},{"x":4,"y":8,"side":"bottom","kind":"item"},{"x":5,"y":8,"side":"bottom","kind":"item"},{"x":6,"y":8,"side":"bottom","kind":"item"},{"x":7,"y":8,"side":"bottom","kind":"item"}],
    outputs: [{"x":0,"y":1,"side":"left","kind":"item"},{"x":0,"y":4,"side":"left","kind":"item"},{"x":0,"y":7,"side":"left","kind":"item"},{"x":8,"y":1,"side":"right","kind":"item"},{"x":8,"y":4,"side":"right","kind":"item"},{"x":8,"y":7,"side":"right","kind":"item"}],
    color: "rgba(255,255,255,0.3)",
    icon: "protocol-core",
    category: "core",
    rarity: "gray",
    notes: "自带200发电，所以耗电量为负。每个出口可以自己选定任意物品从仓库取用输出",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "item-control-port",
    name: "物品准入口",
    nameEn: "Item Control Port",
    power: 0,
    width: 1,
    height: 1,
    inputs: [{"x":0,"y":0,"side":"top","kind":"item"}],
    outputs: [{"x":0,"y":0,"side":"bottom","kind":"item"}],
    color: "rgba(170,255,170,0.3)",
    icon: "item-input-port",
    category: "logistics",
    rarity: "green",
    notes: "可以筛选并且计数通过的物品，可以设定通数量上限（1到5000）。与选定物品不同的物品或者通过数量达到上限会阻碍其继续通行。未设定物品则无效果（当做普通传送带）",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "splitter",
    name: "分流器",
    nameEn: "Splitter",
    power: 0,
    width: 1,
    height: 1,
    inputs: [{"x":0,"y":0,"side":"left","kind":"item"}],
    outputs: [{"x":0,"y":0,"side":"top","kind":"item"},{"x":0,"y":0,"side":"right","kind":"item"},{"x":0,"y":0,"side":"bottom","kind":"item"}],
    color: "rgba(170,255,170,0.3)",
    icon: "splitter",
    category: "logistics",
    rarity: "green",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "belt-bridge",
    name: "物流桥",
    nameEn: "Belt Bridge",
    power: 0,
    width: 1,
    height: 1,
    inputs: [],
    outputs: [],
    color: "rgba(170,255,170,0.3)",
    icon: "logistics-bridge",
    category: "logistics",
    rarity: "green",
    notes: "当两个垂直的传送带相交时自动放置，并且匹配对应传送带的物流方向设定物品出入口。两条传送带可以互不干扰独立运行",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "converger",
    name: "汇流器",
    nameEn: "Converger",
    power: 0,
    width: 1,
    height: 1,
    inputs: [{"x":0,"y":0,"side":"left","kind":"item"},{"x":0,"y":0,"side":"top","kind":"item"},{"x":0,"y":0,"side":"bottom","kind":"item"}],
    outputs: [{"x":0,"y":0,"side":"right","kind":"item"}],
    color: "rgba(170,255,170,0.3)",
    icon: "merger",
    category: "logistics",
    rarity: "green",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "pipe-control-port",
    name: "管道准入口",
    nameEn: "Pipe Control Port",
    power: 0,
    width: 1,
    height: 1,
    inputs: [{"x":0,"y":0,"side":"top","kind":"pipe"}],
    outputs: [{"x":0,"y":0,"side":"bottom","kind":"pipe"}],
    color: "rgba(170,255,170,0.3)",
    icon: "item-input-port",
    category: "logistics",
    rarity: "green",
    notes: "可以筛选并且计数通过的液体，可以设定通数量上限（1到5000）。与选定物品不同的物品或者通过数量达到上限会阻碍其继续通行。未设定物品则无效果（当做普通传管道）",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "pipe-splitter",
    name: "管道分流器",
    nameEn: "Pipe Splitter",
    power: 0,
    width: 1,
    height: 1,
    inputs: [{"x":0,"y":0,"side":"left","kind":"pipe"}],
    outputs: [{"x":0,"y":0,"side":"top","kind":"pipe"},{"x":0,"y":0,"side":"right","kind":"pipe"},{"x":0,"y":0,"side":"bottom","kind":"pipe"}],
    color: "rgba(170,255,170,0.3)",
    icon: "splitter",
    category: "logistics",
    rarity: "green",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "pipe-bridge",
    name: "管道桥",
    nameEn: "Pipe Bridge",
    power: 0,
    width: 1,
    height: 1,
    inputs: [],
    outputs: [],
    color: "rgba(170,255,170,0.3)",
    icon: "logistics-bridge",
    category: "logistics",
    rarity: "green",
    notes: "当两个垂直的管道带相交时自动放置，并且匹配对应传管道的物流方向设定物品出入口。两条管道可以互不干扰独立运行",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "pipe-converger",
    name: "管道汇流器",
    nameEn: "Pipe Converger",
    power: 0,
    width: 1,
    height: 1,
    inputs: [{"x":0,"y":0,"side":"left","kind":"pipe"},{"x":0,"y":0,"side":"top","kind":"pipe"},{"x":0,"y":0,"side":"bottom","kind":"pipe"}],
    outputs: [{"x":0,"y":0,"side":"right","kind":"pipe"}],
    color: "rgba(170,255,170,0.3)",
    icon: "merger",
    category: "logistics",
    rarity: "green",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "belt",
    name: "传送带",
    nameEn: "Belt",
    power: 0,
    width: 1,
    height: 1,
    inputs: [],
    outputs: [],
    color: "rgba(255,255,255,0.3)",
    icon: "logistics-bridge",
    category: "logistics",
    rarity: "gray",
    notes: "2s/物品",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "pipe",
    name: "管道",
    nameEn: "Pipe",
    power: 0,
    width: 1,
    height: 1,
    inputs: [],
    outputs: [],
    color: "rgba(255,255,255,0.3)",
    icon: "logistics-bridge",
    category: "logistics",
    rarity: "gray",
    notes: "2液体/s",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "fluid-pump",
    name: "水泵",
    nameEn: "Fluid Pump",
    power: 10,
    width: 3,
    height: 3,
    inputs: [],
    outputs: [{"x":2,"y":1,"side":"right","kind":"pipe"}],
    color: "rgba(170,255,170,0.3)",
    category: "resourcing",
    rarity: "green",
    notes: "只能放置在基地外",
    placementRule: "outsideOnly",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "acid-resistant-pump-mk-ii",
    name: "二型耐酸水泵",
    nameEn: "Acid Resistant Pump Mk II",
    power: 10,
    width: 3,
    height: 3,
    inputs: [],
    outputs: [{"x":2,"y":1,"side":"right","kind":"pipe"}],
    color: "rgba(170,221,255,0.3)",
    category: "resourcing",
    rarity: "blue",
    notes: "只能放置在基地外",
    placementRule: "outsideOnly",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "fluid-supply-unit",
    name: "给水器",
    nameEn: "Fluid Supply Unit",
    power: 10,
    width: 3,
    height: 3,
    inputs: [{"x":2,"y":1,"side":"right","kind":"pipe"}],
    outputs: [],
    color: "rgba(170,255,170,0.3)",
    category: "resourcing",
    rarity: "green",
    placementRule: "outsideOnly",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "protocol-stash",
    name: "协议储藏箱",
    nameEn: "Protocol Stash",
    power: 5,
    width: 3,
    height: 3,
    inputs: [{"x":0,"y":0,"side":"top","kind":"item"},{"x":1,"y":0,"side":"top","kind":"item"},{"x":2,"y":0,"side":"top","kind":"item"}],
    outputs: [{"x":0,"y":2,"side":"bottom","kind":"item"},{"x":1,"y":2,"side":"bottom","kind":"item"},{"x":2,"y":2,"side":"bottom","kind":"item"}],
    color: "rgba(255,255,255,0.3)",
    icon: "protocol-storage",
    category: "storage",
    rarity: "gray",
    notes: "拥有6个物品格，可连接任意出入口。通电后会每隔10秒尝试吧所有内容物传送到仓库",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "depot-loader",
    name: "仓库存货口",
    nameEn: "Depot Loader",
    power: 0,
    width: 1,
    height: 3,
    inputs: [{"x":0,"y":1,"side":"left","kind":"item"}],
    outputs: [],
    color: "rgba(170,221,255,0.3)",
    icon: "warehouse-storage-port",
    category: "storage",
    rarity: "blue",
    notes: "后背（出入口的对侧）必须与仓库存取线基段或者仓库存取线源桩相连，物品会存入仓库",
    placementRule: "adjacentToSpecialBuilding",
    adjacentToFacilityIds: ["depot-bus-section","depot-bus-port"],
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "depot-unloader",
    name: "仓库取货口",
    nameEn: "Depot Unloader",
    power: 0,
    width: 1,
    height: 3,
    inputs: [],
    outputs: [{"x":0,"y":1,"side":"right","kind":"item"}],
    color: "rgba(170,221,255,0.3)",
    icon: "warehouse-pickup-port",
    category: "storage",
    rarity: "blue",
    notes: "后背（出入口的对侧）必须与仓库存取线基段或者仓库存取线源桩相连，可选定任意物品从仓库取用输出",
    placementRule: "adjacentToSpecialBuilding",
    adjacentToFacilityIds: ["depot-bus-section","depot-bus-port"],
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "fluid-tank",
    name: "储液罐",
    nameEn: "Fluid Tank",
    power: 0,
    width: 3,
    height: 3,
    inputs: [{"x":0,"y":1,"side":"left","kind":"pipe"}],
    outputs: [{"x":2,"y":1,"side":"right","kind":"pipe"}],
    color: "rgba(170,255,170,0.3)",
    icon: "protocol-storage",
    category: "storage",
    rarity: "green",
    notes: "拥有1个能存放500单位液体的物品格，同时链接出入口",
    placementRule: "insideOrOutside",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "depot-bus-section",
    name: "仓库存取线基段",
    nameEn: "Depot Bus Section",
    power: 0,
    width: 4,
    height: 8,
    inputs: [],
    outputs: [],
    color: "rgba(204,136,255,0.3)",
    icon: "warehouse-storage-pickup-line-segment",
    category: "storage",
    rarity: "purple",
    notes: "有放置数量限制，可让用户自定义。必须与仓库存取线源桩相连才可以生效，或者与已经生效的其他仓库存取线基段相连也可以生效",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "depot-bus-port",
    name: "库存取线源桩",
    nameEn: "Depot Bus Port",
    power: 0,
    width: 4,
    height: 4,
    inputs: [],
    outputs: [],
    color: "rgba(204,136,255,0.3)",
    icon: "warehouse-storage-pickup-line-source-pile",
    category: "storage",
    rarity: "purple",
    notes: "有放置数量限制，可让用户自定义",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "conduit-inlet",
    name: "暗管入口",
    nameEn: "Conduit Inlet",
    power: 0,
    width: 3,
    height: 3,
    inputs: [{"x":0,"y":1,"side":"left","kind":"pipe"}],
    outputs: [],
    color: "rgba(170,221,255,0.3)",
    icon: "warehouse-storage-port",
    category: "storage",
    rarity: "blue",
    notes: "必须与另一个暗管出口链接才能启用，拥有1个能存放500单位液体的物品格，链接入口",
    placementRule: "insideOrOutside",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "conduit-outlet",
    name: "暗管出口",
    nameEn: "Conduit Outlet",
    power: 0,
    width: 3,
    height: 3,
    inputs: [],
    outputs: [{"x":2,"y":1,"side":"right","kind":"pipe"}],
    color: "rgba(170,221,255,0.3)",
    icon: "warehouse-pickup-port",
    category: "storage",
    rarity: "blue",
    notes: "必须与另一个暗管入口链接才能启用，拥有1个能存放500单位液体的物品格，链接出口",
    placementRule: "insideOrOutside",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "conduit-inlet-manifold",
    name: "多口暗管入口",
    nameEn: "Conduit Inlet Manifold",
    power: 0,
    width: 3,
    height: 5,
    inputs: [{"x":2,"y":1,"side":"right","kind":"pipe"},{"x":2,"y":3,"side":"right","kind":"pipe"}],
    outputs: [],
    color: "rgba(204,136,255,0.3)",
    icon: "warehouse-storage-port",
    category: "storage",
    rarity: "purple",
    notes: "必须与另一个多口暗管出口链接才能启用，拥有1个能存放500单位液体的物品格，同时链接两个入口",
    placementRule: "insideOrOutside",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "conduit-outlet-manifold",
    name: "多口暗管出口",
    nameEn: "Conduit Outlet Manifold",
    power: 0,
    width: 3,
    height: 5,
    inputs: [],
    outputs: [{"x":2,"y":1,"side":"right","kind":"pipe"},{"x":2,"y":3,"side":"right","kind":"pipe"}],
    color: "rgba(204,136,255,0.3)",
    icon: "warehouse-pickup-port",
    category: "storage",
    rarity: "purple",
    notes: "必须与另一个多口暗管入口链接才能启用，拥有1个能存放500单位液体的物品格，同时链接两个出口",
    placementRule: "insideOrOutside",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "refining-unit",
    name: "精炼炉",
    nameEn: "Refining Unit",
    power: 5,
    width: 3,
    height: 3,
    inputs: [{"x":0,"y":0,"side":"top","kind":"item"},{"x":1,"y":0,"side":"top","kind":"item"},{"x":2,"y":0,"side":"top","kind":"item"},{"x":0,"y":1,"side":"left","kind":"pipe"}],
    outputs: [{"x":0,"y":2,"side":"bottom","kind":"item"},{"x":1,"y":2,"side":"bottom","kind":"item"},{"x":2,"y":2,"side":"bottom","kind":"item"},{"x":2,"y":1,"side":"right","kind":"pipe"}],
    color: "rgba(255,255,255,0.3)",
    icon: "refinery",
    category: "production",
    rarity: "gray",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "shredding-unit",
    name: "粉碎机",
    nameEn: "Shredding Unit",
    power: 5,
    width: 3,
    height: 3,
    inputs: [{"x":0,"y":0,"side":"top","kind":"item"},{"x":1,"y":0,"side":"top","kind":"item"},{"x":2,"y":0,"side":"top","kind":"item"}],
    outputs: [{"x":0,"y":2,"side":"bottom","kind":"item"},{"x":1,"y":2,"side":"bottom","kind":"item"},{"x":2,"y":2,"side":"bottom","kind":"item"}],
    color: "rgba(255,255,255,0.3)",
    icon: "crusher",
    category: "production",
    rarity: "gray",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "fittinguhit",
    name: "配件机",
    nameEn: "FittingUhit",
    power: 20,
    width: 3,
    height: 3,
    inputs: [{"x":0,"y":0,"side":"top","kind":"item"},{"x":1,"y":0,"side":"top","kind":"item"},{"x":2,"y":0,"side":"top","kind":"item"}],
    outputs: [{"x":0,"y":2,"side":"bottom","kind":"item"},{"x":1,"y":2,"side":"bottom","kind":"item"},{"x":2,"y":2,"side":"bottom","kind":"item"}],
    color: "rgba(170,255,170,0.3)",
    icon: "component-assembler",
    category: "production",
    rarity: "green",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "mouldling-unit",
    name: "塑形机",
    nameEn: "Mouldling Unit",
    power: 10,
    width: 3,
    height: 3,
    inputs: [{"x":0,"y":0,"side":"top","kind":"item"},{"x":1,"y":0,"side":"top","kind":"item"},{"x":2,"y":0,"side":"top","kind":"item"}],
    outputs: [{"x":0,"y":2,"side":"bottom","kind":"item"},{"x":1,"y":2,"side":"bottom","kind":"item"},{"x":2,"y":2,"side":"bottom","kind":"item"}],
    color: "rgba(170,255,170,0.3)",
    icon: "molder",
    category: "production",
    rarity: "green",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "planting-unit",
    name: "种植机",
    nameEn: "Planting Unit",
    power: 20,
    width: 5,
    height: 5,
    inputs: [{"x":0,"y":0,"side":"top","kind":"item"},{"x":1,"y":0,"side":"top","kind":"item"},{"x":2,"y":0,"side":"top","kind":"item"},{"x":3,"y":0,"side":"top","kind":"item"},{"x":4,"y":0,"side":"top","kind":"item"},{"x":0,"y":2,"side":"left","kind":"pipe"}],
    outputs: [{"x":0,"y":4,"side":"bottom","kind":"item"},{"x":1,"y":4,"side":"bottom","kind":"item"},{"x":2,"y":4,"side":"bottom","kind":"item"},{"x":3,"y":4,"side":"bottom","kind":"item"},{"x":4,"y":4,"side":"bottom","kind":"item"}],
    color: "rgba(170,221,255,0.3)",
    icon: "planter",
    category: "production",
    rarity: "blue",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "seed-picking-unit",
    name: "采种机",
    nameEn: "Seed-Picking Unit",
    power: 10,
    width: 5,
    height: 5,
    inputs: [{"x":0,"y":0,"side":"top","kind":"item"},{"x":1,"y":0,"side":"top","kind":"item"},{"x":2,"y":0,"side":"top","kind":"item"},{"x":3,"y":0,"side":"top","kind":"item"},{"x":4,"y":0,"side":"top","kind":"item"}],
    outputs: [{"x":0,"y":4,"side":"bottom","kind":"item"},{"x":1,"y":4,"side":"bottom","kind":"item"},{"x":2,"y":4,"side":"bottom","kind":"item"},{"x":3,"y":4,"side":"bottom","kind":"item"},{"x":4,"y":4,"side":"bottom","kind":"item"}],
    color: "rgba(170,221,255,0.3)",
    icon: "seedHarvester",
    category: "production",
    rarity: "blue",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "water-treatment-unit",
    name: "废水处理机",
    nameEn: "Water Treatment Unit",
    power: 50,
    width: 3,
    height: 3,
    inputs: [{"x":0,"y":1,"side":"left","kind":"pipe"}],
    outputs: [],
    color: "rgba(170,221,255,0.3)",
    icon: "refinery",
    category: "production",
    rarity: "blue",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "gearing-unit",
    name: "装备原件机",
    nameEn: "Gearing Unit",
    power: 10,
    width: 6,
    height: 4,
    inputs: [{"x":0,"y":0,"side":"top","kind":"item"},{"x":1,"y":0,"side":"top","kind":"item"},{"x":2,"y":0,"side":"top","kind":"item"},{"x":3,"y":0,"side":"top","kind":"item"},{"x":4,"y":0,"side":"top","kind":"item"},{"x":5,"y":0,"side":"top","kind":"item"}],
    outputs: [{"x":0,"y":3,"side":"bottom","kind":"item"},{"x":1,"y":3,"side":"bottom","kind":"item"},{"x":2,"y":3,"side":"bottom","kind":"item"},{"x":3,"y":3,"side":"bottom","kind":"item"},{"x":4,"y":3,"side":"bottom","kind":"item"},{"x":5,"y":3,"side":"bottom","kind":"item"}],
    color: "rgba(255,255,255,0.3)",
    icon: "component-assembler",
    category: "processing",
    rarity: "gray",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "filling-unit",
    name: "灌装机",
    nameEn: "Filling Unit",
    power: 20,
    width: 6,
    height: 4,
    inputs: [{"x":0,"y":0,"side":"top","kind":"item"},{"x":1,"y":0,"side":"top","kind":"item"},{"x":2,"y":0,"side":"top","kind":"item"},{"x":3,"y":0,"side":"top","kind":"item"},{"x":4,"y":0,"side":"top","kind":"item"},{"x":5,"y":0,"side":"top","kind":"item"},{"x":0,"y":1,"side":"left","kind":"pipe"}],
    outputs: [{"x":0,"y":3,"side":"bottom","kind":"item"},{"x":1,"y":3,"side":"bottom","kind":"item"},{"x":2,"y":3,"side":"bottom","kind":"item"},{"x":3,"y":3,"side":"bottom","kind":"item"},{"x":4,"y":3,"side":"bottom","kind":"item"},{"x":5,"y":3,"side":"bottom","kind":"item"}],
    color: "rgba(170,221,255,0.3)",
    icon: "filler",
    category: "processing",
    rarity: "blue",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "packaging-unit",
    name: "封装机",
    nameEn: "Packaging Unit",
    power: 20,
    width: 6,
    height: 4,
    inputs: [{"x":0,"y":0,"side":"top","kind":"item"},{"x":1,"y":0,"side":"top","kind":"item"},{"x":2,"y":0,"side":"top","kind":"item"},{"x":3,"y":0,"side":"top","kind":"item"},{"x":4,"y":0,"side":"top","kind":"item"},{"x":5,"y":0,"side":"top","kind":"item"}],
    outputs: [{"x":0,"y":3,"side":"bottom","kind":"item"},{"x":1,"y":3,"side":"bottom","kind":"item"},{"x":2,"y":3,"side":"bottom","kind":"item"},{"x":3,"y":3,"side":"bottom","kind":"item"},{"x":4,"y":3,"side":"bottom","kind":"item"},{"x":5,"y":3,"side":"bottom","kind":"item"}],
    color: "rgba(170,221,255,0.3)",
    icon: "sealer",
    category: "processing",
    rarity: "blue",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "grinding-unit",
    name: "研磨机",
    nameEn: "Grinding Unit",
    power: 50,
    width: 6,
    height: 4,
    inputs: [{"x":0,"y":0,"side":"top","kind":"item"},{"x":1,"y":0,"side":"top","kind":"item"},{"x":2,"y":0,"side":"top","kind":"item"},{"x":3,"y":0,"side":"top","kind":"item"},{"x":4,"y":0,"side":"top","kind":"item"},{"x":5,"y":0,"side":"top","kind":"item"}],
    outputs: [{"x":0,"y":3,"side":"bottom","kind":"item"},{"x":1,"y":3,"side":"bottom","kind":"item"},{"x":2,"y":3,"side":"bottom","kind":"item"},{"x":3,"y":3,"side":"bottom","kind":"item"},{"x":4,"y":3,"side":"bottom","kind":"item"},{"x":5,"y":3,"side":"bottom","kind":"item"}],
    color: "rgba(204,136,255,0.3)",
    icon: "grinder",
    category: "processing",
    rarity: "purple",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "reactor-crucible",
    name: "反应池",
    nameEn: "Reactor Crucible",
    power: 50,
    width: 5,
    height: 5,
    inputs: [{"x":1,"y":0,"side":"top","kind":"item"},{"x":3,"y":0,"side":"top","kind":"item"},{"x":0,"y":1,"side":"left","kind":"pipe"},{"x":0,"y":3,"side":"left","kind":"pipe"}],
    outputs: [{"x":1,"y":4,"side":"bottom","kind":"item"},{"x":3,"y":4,"side":"bottom","kind":"item"},{"x":4,"y":1,"side":"right","kind":"pipe"},{"x":4,"y":3,"side":"right","kind":"pipe"}],
    color: "rgba(170,221,255,0.3)",
    icon: "reactor",
    category: "processing",
    rarity: "blue",
    notes: "可同时进行多个配方生产，拥有5个物品格，物品液体均可存放，可连接任意出入口。液体出口需要手动指定，未指定则不输出液体",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "expanded-crucible",
    name: "扩容反应池",
    nameEn: "Expanded Crucible",
    power: 100,
    width: 6,
    height: 5,
    inputs: [{"x":1,"y":0,"side":"top","kind":"item"},{"x":2,"y":0,"side":"top","kind":"item"},{"x":3,"y":0,"side":"top","kind":"item"},{"x":4,"y":0,"side":"top","kind":"item"},{"x":0,"y":1,"side":"left","kind":"pipe"},{"x":0,"y":3,"side":"left","kind":"pipe"}],
    outputs: [{"x":1,"y":4,"side":"bottom","kind":"item"},{"x":2,"y":4,"side":"bottom","kind":"item"},{"x":3,"y":4,"side":"bottom","kind":"item"},{"x":4,"y":4,"side":"bottom","kind":"item"},{"x":5,"y":1,"side":"right","kind":"pipe"},{"x":5,"y":3,"side":"right","kind":"pipe"}],
    color: "rgba(170,221,255,0.3)",
    icon: "reactor",
    category: "processing",
    rarity: "blue",
    notes: "可同时进行多个配方生产，拥有7个物品格，物品液体均可存放，可连接任意出入口。液体出口需要手动指定，未指定则不输出液体",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "forge-of-the-sky",
    name: "天有洪炉",
    nameEn: "Forge of the Sky",
    power: 50,
    width: 5,
    height: 5,
    inputs: [{"x":0,"y":0,"side":"top","kind":"item"},{"x":1,"y":0,"side":"top","kind":"item"},{"x":2,"y":0,"side":"top","kind":"item"},{"x":3,"y":0,"side":"top","kind":"item"},{"x":4,"y":0,"side":"top","kind":"item"},{"x":0,"y":2,"side":"left","kind":"pipe"}],
    outputs: [{"x":0,"y":4,"side":"bottom","kind":"item"},{"x":1,"y":4,"side":"bottom","kind":"item"},{"x":2,"y":4,"side":"bottom","kind":"item"},{"x":3,"y":4,"side":"bottom","kind":"item"},{"x":4,"y":4,"side":"bottom","kind":"item"}],
    color: "rgba(204,136,255,0.3)",
    icon: "tian-you-hong-furnace",
    category: "processing",
    rarity: "purple",
    notes: "有放置数量限制，可让用户自定义",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "puritication-unit",
    name: "提纯机",
    nameEn: "Puritication Unit",
    power: 50,
    width: 5,
    height: 5,
    inputs: [{"x":0,"y":1,"side":"left","kind":"pipe"},{"x":0,"y":3,"side":"left","kind":"pipe"}],
    outputs: [{"x":4,"y":1,"side":"right","kind":"pipe"},{"x":4,"y":3,"side":"right","kind":"pipe"}],
    color: "rgba(204,136,255,0.3)",
    icon: "refinery",
    category: "processing",
    rarity: "purple",
    placementRule: "insideOrOutside",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "separating-unit",
    name: "拆解机",
    nameEn: "Separating Unit",
    power: 20,
    width: 6,
    height: 4,
    inputs: [{"x":0,"y":0,"side":"top","kind":"item"},{"x":1,"y":0,"side":"top","kind":"item"},{"x":2,"y":0,"side":"top","kind":"item"},{"x":3,"y":0,"side":"top","kind":"item"},{"x":4,"y":0,"side":"top","kind":"item"},{"x":5,"y":0,"side":"top","kind":"item"}],
    outputs: [{"x":0,"y":3,"side":"bottom","kind":"item"},{"x":1,"y":3,"side":"bottom","kind":"item"},{"x":2,"y":3,"side":"bottom","kind":"item"},{"x":3,"y":3,"side":"bottom","kind":"item"},{"x":4,"y":3,"side":"bottom","kind":"item"},{"x":5,"y":3,"side":"bottom","kind":"item"},{"x":5,"y":1,"side":"right","kind":"pipe"}],
    color: "rgba(204,136,255,0.3)",
    icon: "sealer",
    category: "processing",
    rarity: "purple",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "electric-pylon",
    name: "供电桩",
    nameEn: "Electric Pylon",
    power: 0,
    width: 2,
    height: 2,
    inputs: [],
    outputs: [],
    color: "rgba(255,255,255,0.3)",
    icon: "supply-pole",
    category: "power",
    rarity: "gray",
    supplyRange: 12,
    notes: "供电范围是物品为中心的12*12格",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "xiranite-pylon",
    name: "息壤供电桩",
    nameEn: "Xiranite Pylon",
    power: 0,
    width: 2,
    height: 2,
    inputs: [],
    outputs: [],
    color: "rgba(255,255,255,0.3)",
    icon: "supply-pole",
    category: "power",
    rarity: "gray",
    supplyRange: 12,
    notes: "供电范围是物品为中心的12*12格",
    allowedItems: Object.values(ITEMS),
  },
  {
    id: "thermal-bank",
    name: "热能池",
    nameEn: "Thermal Bank",
    power: 0,
    width: 2,
    height: 2,
    inputs: [{"x":0,"y":0,"side":"top","kind":"item"},{"x":1,"y":0,"side":"top","kind":"item"}],
    outputs: [],
    color: "rgba(170,255,170,0.3)",
    icon: "thermal-pool",
    category: "power",
    rarity: "green",
    allowedItems: Object.values(ITEMS),
  }
];

export const MACHINES = FACILITIES;
export const getFacilityConfig = (id: string) => FACILITIES.find(facility => facility.id === id);
export const getMachineConfig = getFacilityConfig;
