import type { MachineConfig } from '../types';
import { ITEMS } from './items';

export const FACILITIES: MachineConfig[] = [
  {
    id: 'automation-core',
    name: '协议核心',
    nameEn: 'Automation-Core',
    power: -200,
    width: 9,
    height: 9,
    inputs: [{"x": 1, "y": 0, "side": "top"}, {"x": 2, "y": 0, "side": "top"}, {"x": 3, "y": 0, "side": "top"}, {"x": 4, "y": 0, "side": "top"}, {"x": 5, "y": 0, "side": "top"}, {"x": 6, "y": 0, "side": "top"}, {"x": 7, "y": 0, "side": "top"}, {"x": 1, "y": 8, "side": "bottom"}, {"x": 2, "y": 8, "side": "bottom"}, {"x": 3, "y": 8, "side": "bottom"}, {"x": 4, "y": 8, "side": "bottom"}, {"x": 5, "y": 8, "side": "bottom"}, {"x": 6, "y": 8, "side": "bottom"}, {"x": 7, "y": 8, "side": "bottom"}],
    outputs: [{"x": 0, "y": 1, "side": "left"}, {"x": 0, "y": 4, "side": "left"}, {"x": 0, "y": 7, "side": "left"}, {"x": 8, "y": 1, "side": "right"}, {"x": 8, "y": 4, "side": "right"}, {"x": 8, "y": 7, "side": "right"}],
    color: 'rgba(255,255,255,0.3)',
    category: 'misc',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'item-control-port',
    name: '物品准入口',
    nameEn: 'Item Control Port',
    power: 0,
    width: 1,
    height: 1,
    inputs: [{"x": 0, "y": 0, "side": "top"}],
    outputs: [{"x": 0, "y": 0, "side": "bottom"}],
    color: 'rgba(170,255,170,0.3)',
    category: 'logistics',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'splitter',
    name: '分流器',
    nameEn: 'Splitter',
    power: 0,
    width: 1,
    height: 1,
    inputs: [{"x": 0, "y": 0, "side": "left"}],
    outputs: [{"x": 0, "y": 0, "side": "top"}, {"x": 0, "y": 0, "side": "right"}, {"x": 0, "y": 0, "side": "bottom"}],
    color: 'rgba(170,255,170,0.3)',
    category: 'logistics',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'belt-bridge',
    name: '物流桥',
    nameEn: 'Belt Bridge',
    power: 0,
    width: 1,
    height: 1,
    inputs: [],
    outputs: [],
    color: 'rgba(170,255,170,0.3)',
    category: 'logistics',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'converger',
    name: '汇流器',
    nameEn: 'Converger',
    power: 0,
    width: 1,
    height: 1,
    inputs: [{"x": 0, "y": 0, "side": "left"}, {"x": 0, "y": 0, "side": "top"}, {"x": 0, "y": 0, "side": "bottom"}],
    outputs: [{"x": 0, "y": 0, "side": "right"}],
    color: 'rgba(170,255,170,0.3)',
    category: 'logistics',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'pipe-control-port',
    name: '管道准入口',
    nameEn: 'Pipe Control Port',
    power: 0,
    width: 1,
    height: 1,
    inputs: [{"x": 0, "y": 0, "side": "top"}],
    outputs: [{"x": 0, "y": 0, "side": "bottom"}],
    color: 'rgba(170,255,170,0.3)',
    category: 'logistics',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'pipe-splitter',
    name: '管道分流器',
    nameEn: 'Pipe Splitter',
    power: 0,
    width: 1,
    height: 1,
    inputs: [{"x": 0, "y": 0, "side": "left"}],
    outputs: [{"x": 0, "y": 0, "side": "top"}, {"x": 0, "y": 0, "side": "right"}, {"x": 0, "y": 0, "side": "bottom"}],
    color: 'rgba(170,255,170,0.3)',
    category: 'logistics',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'pipe-bridge',
    name: '管道桥',
    nameEn: 'Pipe Bridge',
    power: 0,
    width: 1,
    height: 1,
    inputs: [],
    outputs: [],
    color: 'rgba(170,255,170,0.3)',
    category: 'logistics',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'pipe-converger',
    name: '管道汇流器',
    nameEn: 'Pipe Converger',
    power: 0,
    width: 1,
    height: 1,
    inputs: [{"x": 0, "y": 0, "side": "left"}, {"x": 0, "y": 0, "side": "top"}, {"x": 0, "y": 0, "side": "bottom"}],
    outputs: [{"x": 0, "y": 0, "side": "right"}],
    color: 'rgba(170,255,170,0.3)',
    category: 'logistics',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'belt',
    name: '传送带',
    nameEn: 'Belt',
    power: 0,
    width: 1,
    height: 1,
    inputs: [],
    outputs: [],
    color: 'rgba(255,255,255,0.3)',
    category: 'logistics',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'pipe',
    name: '管道',
    nameEn: 'Pipe',
    power: 0,
    width: 1,
    height: 1,
    inputs: [],
    outputs: [],
    color: 'rgba(255,255,255,0.3)',
    category: 'logistics',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'protocol-stash',
    name: '协议储藏箱',
    nameEn: 'Protocol Stash',
    power: 0,
    width: 3,
    height: 3,
    inputs: [{"x": 0, "y": 0, "side": "top"}, {"x": 1, "y": 0, "side": "top"}, {"x": 2, "y": 0, "side": "top"}],
    outputs: [{"x": 0, "y": 2, "side": "bottom"}, {"x": 1, "y": 2, "side": "bottom"}, {"x": 2, "y": 2, "side": "bottom"}],
    color: 'rgba(255,255,255,0.3)',
    category: 'storage',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'depot-loader',
    name: '仓库存货口',
    nameEn: 'Depot Loader',
    power: 0,
    width: 1,
    height: 3,
    inputs: [{"x": 0, "y": 1, "side": "left"}],
    outputs: [],
    color: 'rgba(170,221,255,0.3)',
    category: 'storage',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'depot-unloader',
    name: '仓库取货口',
    nameEn: 'Depot Unloader',
    power: 0,
    width: 1,
    height: 3,
    inputs: [],
    outputs: [{"x": 0, "y": 1, "side": "right"}],
    color: 'rgba(170,221,255,0.3)',
    category: 'storage',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'fluid-tank',
    name: '储液罐',
    nameEn: 'Fluid Tank',
    power: 0,
    width: 3,
    height: 3,
    inputs: [{"x": 0, "y": 1, "side": "left"}],
    outputs: [{"x": 2, "y": 1, "side": "right"}],
    color: 'rgba(170,255,170,0.3)',
    category: 'storage',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'depot-bus-section',
    name: '仓库存取线基段',
    nameEn: 'Depot Bus Section',
    power: 0,
    width: 4,
    height: 8,
    inputs: [],
    outputs: [],
    color: 'rgba(204,136,255,0.3)',
    category: 'storage',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'depot-bus-port',
    name: '库存取线源桩',
    nameEn: 'Depot Bus Port',
    power: 0,
    width: 4,
    height: 4,
    inputs: [],
    outputs: [],
    color: 'rgba(204,136,255,0.3)',
    category: 'storage',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'conduit-inlet',
    name: '暗管入口',
    nameEn: 'Conduit Inlet',
    power: 0,
    width: 3,
    height: 3,
    inputs: [{"x": 0, "y": 1, "side": "left"}],
    outputs: [],
    color: 'rgba(170,221,255,0.3)',
    category: 'storage',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'conduit-outlet',
    name: '暗管出口',
    nameEn: 'Conduit Outlet',
    power: 0,
    width: 3,
    height: 3,
    inputs: [],
    outputs: [{"x": 2, "y": 1, "side": "right"}],
    color: 'rgba(170,221,255,0.3)',
    category: 'storage',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'conduit-inlet-manifold',
    name: '多口暗管入口',
    nameEn: 'Conduit Inlet Manifold',
    power: 0,
    width: 3,
    height: 5,
    inputs: [{"x": 2, "y": 1, "side": "right"}, {"x": 2, "y": 3, "side": "right"}],
    outputs: [],
    color: 'rgba(204,136,255,0.3)',
    category: 'storage',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'conduit-outlet-manifold',
    name: '多口暗管出口',
    nameEn: 'Conduit Outlet Manifold',
    power: 0,
    width: 3,
    height: 5,
    inputs: [],
    outputs: [{"x": 2, "y": 1, "side": "right"}, {"x": 2, "y": 3, "side": "right"}],
    color: 'rgba(204,136,255,0.3)',
    category: 'storage',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'refining-unit',
    name: '精炼炉',
    nameEn: 'Refining Unit',
    power: 5,
    width: 3,
    height: 3,
    inputs: [{"x": 0, "y": 0, "side": "top"}, {"x": 1, "y": 0, "side": "top"}, {"x": 2, "y": 0, "side": "top"}, {"x": 0, "y": 1, "side": "left"}],
    outputs: [{"x": 0, "y": 2, "side": "bottom"}, {"x": 1, "y": 2, "side": "bottom"}, {"x": 2, "y": 2, "side": "bottom"}, {"x": 2, "y": 1, "side": "right"}],
    color: 'rgba(255,255,255,0.3)',
    category: 'production_i',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'shredding-unit',
    name: '粉碎机',
    nameEn: 'Shredding Unit',
    power: 5,
    width: 3,
    height: 3,
    inputs: [{"x": 0, "y": 0, "side": "top"}, {"x": 1, "y": 0, "side": "top"}, {"x": 2, "y": 0, "side": "top"}],
    outputs: [{"x": 0, "y": 2, "side": "bottom"}, {"x": 1, "y": 2, "side": "bottom"}, {"x": 2, "y": 2, "side": "bottom"}],
    color: 'rgba(255,255,255,0.3)',
    category: 'production_i',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'fittinguhit',
    name: '配件机',
    nameEn: 'FittingUhit',
    power: 20,
    width: 3,
    height: 3,
    inputs: [{"x": 0, "y": 0, "side": "top"}, {"x": 1, "y": 0, "side": "top"}, {"x": 2, "y": 0, "side": "top"}],
    outputs: [{"x": 0, "y": 2, "side": "bottom"}, {"x": 1, "y": 2, "side": "bottom"}, {"x": 2, "y": 2, "side": "bottom"}],
    color: 'rgba(170,255,170,0.3)',
    category: 'production_i',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'mouldling-unit',
    name: '塑形机',
    nameEn: 'Mouldling Unit',
    power: 10,
    width: 3,
    height: 3,
    inputs: [{"x": 0, "y": 0, "side": "top"}, {"x": 1, "y": 0, "side": "top"}, {"x": 2, "y": 0, "side": "top"}],
    outputs: [{"x": 0, "y": 2, "side": "bottom"}, {"x": 1, "y": 2, "side": "bottom"}, {"x": 2, "y": 2, "side": "bottom"}],
    color: 'rgba(170,255,170,0.3)',
    category: 'production_i',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'planting-unit',
    name: '种植机',
    nameEn: 'Planting Unit',
    power: 20,
    width: 5,
    height: 5,
    inputs: [{"x": 0, "y": 0, "side": "top"}, {"x": 1, "y": 0, "side": "top"}, {"x": 2, "y": 0, "side": "top"}, {"x": 3, "y": 0, "side": "top"}, {"x": 4, "y": 0, "side": "top"}, {"x": 0, "y": 2, "side": "left"}],
    outputs: [{"x": 0, "y": 4, "side": "bottom"}, {"x": 1, "y": 4, "side": "bottom"}, {"x": 2, "y": 4, "side": "bottom"}, {"x": 3, "y": 4, "side": "bottom"}, {"x": 4, "y": 4, "side": "bottom"}],
    color: 'rgba(170,221,255,0.3)',
    category: 'production_i',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'seed-picking-unit',
    name: '采种机',
    nameEn: 'Seed-Picking Unit',
    power: 10,
    width: 5,
    height: 5,
    inputs: [{"x": 0, "y": 0, "side": "top"}, {"x": 1, "y": 0, "side": "top"}, {"x": 2, "y": 0, "side": "top"}, {"x": 3, "y": 0, "side": "top"}, {"x": 4, "y": 0, "side": "top"}],
    outputs: [{"x": 0, "y": 4, "side": "bottom"}, {"x": 1, "y": 4, "side": "bottom"}, {"x": 2, "y": 4, "side": "bottom"}, {"x": 3, "y": 4, "side": "bottom"}, {"x": 4, "y": 4, "side": "bottom"}],
    color: 'rgba(170,221,255,0.3)',
    category: 'production_i',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'water-treatment-unit',
    name: '废水处理机',
    nameEn: 'Water Treatment Unit',
    power: 50,
    width: 3,
    height: 3,
    inputs: [{"x": 0, "y": 1, "side": "left"}],
    outputs: [],
    color: 'rgba(170,221,255,0.3)',
    category: 'production_i',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'gearing-unit',
    name: '装备原件机',
    nameEn: 'Gearing Unit',
    power: 10,
    width: 6,
    height: 4,
    inputs: [{"x": 0, "y": 0, "side": "top"}, {"x": 1, "y": 0, "side": "top"}, {"x": 2, "y": 0, "side": "top"}, {"x": 3, "y": 0, "side": "top"}, {"x": 4, "y": 0, "side": "top"}, {"x": 5, "y": 0, "side": "top"}],
    outputs: [{"x": 0, "y": 3, "side": "bottom"}, {"x": 1, "y": 3, "side": "bottom"}, {"x": 2, "y": 3, "side": "bottom"}, {"x": 3, "y": 3, "side": "bottom"}, {"x": 4, "y": 3, "side": "bottom"}, {"x": 5, "y": 3, "side": "bottom"}],
    color: 'rgba(255,255,255,0.3)',
    category: 'production_ii',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'filling-unit',
    name: '灌装机',
    nameEn: 'Filling Unit',
    power: 20,
    width: 6,
    height: 4,
    inputs: [{"x": 0, "y": 0, "side": "top"}, {"x": 1, "y": 0, "side": "top"}, {"x": 2, "y": 0, "side": "top"}, {"x": 3, "y": 0, "side": "top"}, {"x": 4, "y": 0, "side": "top"}, {"x": 5, "y": 0, "side": "top"}, {"x": 0, "y": 1, "side": "left"}],
    outputs: [{"x": 0, "y": 3, "side": "bottom"}, {"x": 1, "y": 3, "side": "bottom"}, {"x": 2, "y": 3, "side": "bottom"}, {"x": 3, "y": 3, "side": "bottom"}, {"x": 4, "y": 3, "side": "bottom"}, {"x": 5, "y": 3, "side": "bottom"}],
    color: 'rgba(170,221,255,0.3)',
    category: 'production_ii',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'packaging-unit',
    name: '封装机',
    nameEn: 'Packaging Unit',
    power: 20,
    width: 6,
    height: 4,
    inputs: [{"x": 0, "y": 0, "side": "top"}, {"x": 1, "y": 0, "side": "top"}, {"x": 2, "y": 0, "side": "top"}, {"x": 3, "y": 0, "side": "top"}, {"x": 4, "y": 0, "side": "top"}, {"x": 5, "y": 0, "side": "top"}],
    outputs: [{"x": 0, "y": 3, "side": "bottom"}, {"x": 1, "y": 3, "side": "bottom"}, {"x": 2, "y": 3, "side": "bottom"}, {"x": 3, "y": 3, "side": "bottom"}, {"x": 4, "y": 3, "side": "bottom"}, {"x": 5, "y": 3, "side": "bottom"}],
    color: 'rgba(170,221,255,0.3)',
    category: 'production_ii',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'grinding-unit',
    name: '研磨机',
    nameEn: 'Grinding Unit',
    power: 50,
    width: 6,
    height: 4,
    inputs: [{"x": 0, "y": 0, "side": "top"}, {"x": 1, "y": 0, "side": "top"}, {"x": 2, "y": 0, "side": "top"}, {"x": 3, "y": 0, "side": "top"}, {"x": 4, "y": 0, "side": "top"}, {"x": 5, "y": 0, "side": "top"}],
    outputs: [{"x": 0, "y": 3, "side": "bottom"}, {"x": 1, "y": 3, "side": "bottom"}, {"x": 2, "y": 3, "side": "bottom"}, {"x": 3, "y": 3, "side": "bottom"}, {"x": 4, "y": 3, "side": "bottom"}, {"x": 5, "y": 3, "side": "bottom"}],
    color: 'rgba(204,136,255,0.3)',
    category: 'production_ii',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'reactor-crucible',
    name: '反应池',
    nameEn: 'Reactor Crucible',
    power: 50,
    width: 5,
    height: 5,
    inputs: [{"x": 1, "y": 0, "side": "top"}, {"x": 3, "y": 0, "side": "top"}, {"x": 0, "y": 1, "side": "left"}, {"x": 0, "y": 3, "side": "left"}],
    outputs: [{"x": 1, "y": 4, "side": "bottom"}, {"x": 3, "y": 4, "side": "bottom"}, {"x": 4, "y": 1, "side": "right"}, {"x": 4, "y": 3, "side": "right"}],
    color: 'rgba(170,221,255,0.3)',
    category: 'production_ii',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'expanded-crucible',
    name: '扩容反应池',
    nameEn: 'Expanded Crucible',
    power: 100,
    width: 6,
    height: 5,
    inputs: [{"x": 1, "y": 0, "side": "top"}, {"x": 2, "y": 0, "side": "top"}, {"x": 3, "y": 0, "side": "top"}, {"x": 4, "y": 0, "side": "top"}, {"x": 0, "y": 1, "side": "left"}, {"x": 0, "y": 3, "side": "left"}],
    outputs: [{"x": 1, "y": 4, "side": "bottom"}, {"x": 2, "y": 4, "side": "bottom"}, {"x": 3, "y": 4, "side": "bottom"}, {"x": 4, "y": 4, "side": "bottom"}, {"x": 5, "y": 1, "side": "right"}, {"x": 5, "y": 3, "side": "right"}],
    color: 'rgba(170,221,255,0.3)',
    category: 'production_ii',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'forge-of-the-sky',
    name: '天有洪炉',
    nameEn: 'Forge of the Sky',
    power: 50,
    width: 5,
    height: 5,
    inputs: [{"x": 0, "y": 0, "side": "top"}, {"x": 1, "y": 0, "side": "top"}, {"x": 2, "y": 0, "side": "top"}, {"x": 3, "y": 0, "side": "top"}, {"x": 4, "y": 0, "side": "top"}, {"x": 0, "y": 2, "side": "left"}],
    outputs: [{"x": 0, "y": 4, "side": "bottom"}, {"x": 1, "y": 4, "side": "bottom"}, {"x": 2, "y": 4, "side": "bottom"}, {"x": 3, "y": 4, "side": "bottom"}, {"x": 4, "y": 4, "side": "bottom"}],
    color: 'rgba(204,136,255,0.3)',
    category: 'production_ii',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'puritication-unit',
    name: '提纯机',
    nameEn: 'Puritication Unit',
    power: 50,
    width: 5,
    height: 5,
    inputs: [{"x": 0, "y": 1, "side": "left"}, {"x": 0, "y": 3, "side": "left"}],
    outputs: [{"x": 4, "y": 1, "side": "right"}, {"x": 4, "y": 3, "side": "right"}],
    color: 'rgba(204,136,255,0.3)',
    category: 'production_ii',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'separating-unit',
    name: '拆解机',
    nameEn: 'Separating Unit',
    power: 20,
    width: 6,
    height: 4,
    inputs: [{"x": 0, "y": 0, "side": "top"}, {"x": 1, "y": 0, "side": "top"}, {"x": 2, "y": 0, "side": "top"}, {"x": 3, "y": 0, "side": "top"}, {"x": 4, "y": 0, "side": "top"}, {"x": 5, "y": 0, "side": "top"}],
    outputs: [{"x": 0, "y": 3, "side": "bottom"}, {"x": 1, "y": 3, "side": "bottom"}, {"x": 2, "y": 3, "side": "bottom"}, {"x": 3, "y": 3, "side": "bottom"}, {"x": 4, "y": 3, "side": "bottom"}, {"x": 5, "y": 3, "side": "bottom"}, {"x": 5, "y": 1, "side": "right"}],
    color: 'rgba(204,136,255,0.3)',
    category: 'production_ii',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'electric-pylon',
    name: '供电桩',
    nameEn: 'Electric Pylon',
    power: 0,
    width: 2,
    height: 2,
    inputs: [],
    outputs: [],
    color: 'rgba(255,255,255,0.3)',
    category: 'power',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'xiranite-pylon',
    name: '息壤供电桩',
    nameEn: 'Xiranite Pylon',
    power: 0,
    width: 2,
    height: 2,
    inputs: [],
    outputs: [],
    color: 'rgba(255,255,255,0.3)',
    category: 'power',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
  {
    id: 'thermal-bank',
    name: '热能池',
    nameEn: 'Thermal Bank',
    power: 0,
    width: 2,
    height: 2,
    inputs: [{"x": 0, "y": 0, "side": "top"}, {"x": 1, "y": 0, "side": "top"}],
    outputs: [],
    color: 'rgba(170,255,170,0.3)',
    category: 'power',
    allowedItems: Object.values(ITEMS),
    allowedMaterials: Object.values(ITEMS),
  },
];

export const MACHINES = FACILITIES;
export const getFacilityConfig = (id: string) => FACILITIES.find(m => m.id === id);
export const getMachineConfig = getFacilityConfig;